// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String?> deleteToTrash({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleDeleteToTrash(filePath: filePath);

Future<String?> deleteAllToTrash({required List<String> filePaths}) =>
    RustLib.instance.api.crateApiSimpleDeleteAllToTrash(filePaths: filePaths);

Future<bool> hasPngTransparencyRust({required String filePath}) => RustLib
    .instance
    .api
    .crateApiSimpleHasPngTransparencyRust(filePath: filePath);

Future<List<ResultBoolString>> hasPngTransparencyBatchRust({
  required List<String> filePaths,
}) => RustLib.instance.api.crateApiSimpleHasPngTransparencyBatchRust(
  filePaths: filePaths,
);

Future<List<String>> deleteTransparentPngsRust({
  required List<String> filePaths,
}) => RustLib.instance.api.crateApiSimpleDeleteTransparentPngsRust(
  filePaths: filePaths,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Result < bool , String >>>
abstract class ResultBoolString implements RustOpaqueInterface {}
